version: '3.8'

services:
  server1:
    build:
      context: ./Server1
    ports:
      - "6000"  # Expose only internally for load balancer

  server2:
    build:
      context: ./Server3
    ports:
      - "7000"  # Expose only internally for load balancer

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Expose NGINX to the outside world
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2